Repository organization/Kookie, pull requests merged in 2021-06, with the labels that each got.

#17 hotfix: (Vector3 / Pos*) - float to double
  app/src/main/kotlin/be/zvz/kookie/block/Block.kt
  app/src/main/kotlin/be/zvz/kookie/entity/Location.kt
  app/src/main/kotlin/be/zvz/kookie/math/AxisAlignedBB.kt
  app/src/main/kotlin/be/zvz/kookie/math/Vector2.kt
  app/src/main/kotlin/be/zvz/kookie/math/Vector3.kt
  app/src/main/kotlin/be/zvz/kookie/network/mcpe/protocol/serializer/PacketSerializer.kt
  app/src/main/kotlin/be/zvz/kookie/world/Position.kt
Labels: bug

#11 feature: block & items
  app/src/main/kotlin/be/zvz/kookie/entity/Consumable.kt
  app/src/main/kotlin/be/zvz/kookie/entity/FoodSource.kt
  app/src/main/kotlin/be/zvz/kookie/entity/effect/Effect.kt
  app/src/main/kotlin/be/zvz/kookie/entity/effect/EffectInstance.kt
  app/src/main/kotlin/be/zvz/kookie/event/EntityDamageEvent.kt
  app/src/main/kotlin/be/zvz/kookie/event/Event.kt
  app/src/main/kotlin/be/zvz/kookie/inventory/BaseInventory.kt
  app/src/main/kotlin/be/zvz/kookie/inventory/Inventory.kt
  app/src/main/kotlin/be/zvz/kookie/inventory/InventoryHelpers.kt
  app/src/main/kotlin/be/zvz/kookie/inventory/SimpleInventory.kt
  app/src/main/kotlin/be/zvz/kookie/item/Apple.kt
  app/src/main/kotlin/be/zvz/kookie/item/Armor.kt
  app/src/main/kotlin/be/zvz/kookie/item/ArmorTypeInfo.kt
  app/src/main/kotlin/be/zvz/kookie/item/Arrow.kt
  app/src/main/kotlin/be/zvz/kookie/item/Axe.kt
  app/src/main/kotlin/be/zvz/kookie/item/ConsumableItem.kt
  app/src/main/kotlin/be/zvz/kookie/item/Durable.kt
  app/src/main/kotlin/be/zvz/kookie/item/Food.kt
  app/src/main/kotlin/be/zvz/kookie/item/FoodSourceItem.kt
  app/src/main/kotlin/be/zvz/kookie/item/Hoe.kt
  app/src/main/kotlin/be/zvz/kookie/item/Item.kt
  app/src/main/kotlin/be/zvz/kookie/item/ItemFactory.kt
  app/src/main/kotlin/be/zvz/kookie/item/ItemIds.kt
  app/src/main/kotlin/be/zvz/kookie/item/Pickaxe.kt
  app/src/main/kotlin/be/zvz/kookie/item/Releasable.kt
  app/src/main/kotlin/be/zvz/kookie/item/Shovel.kt
  app/src/main/kotlin/be/zvz/kookie/item/Sword.kt
  app/src/main/kotlin/be/zvz/kookie/item/TieredTool.kt
  app/src/main/kotlin/be/zvz/kookie/item/Tool.kt
  app/src/main/kotlin/be/zvz/kookie/item/ToolTier.kt
  app/src/main/kotlin/be/zvz/kookie/item/enchantment/ProtectionEnchantment.kt
  app/src/main/kotlin/be/zvz/kookie/player/Player.kt
Labels: enhancement, high priority

#30 style : clean code
  app/src/main/kotlin/be/zvz/kookie/ServerConfigGroup.kt
  app/src/main/kotlin/be/zvz/kookie/block/Block.kt
  app/src/main/kotlin/be/zvz/kookie/block/BlockIdentifier.kt
  app/src/main/kotlin/be/zvz/kookie/command/Command.kt
  app/src/main/kotlin/be/zvz/kookie/command/ConsoleCommandSender.kt
  app/src/main/kotlin/be/zvz/kookie/inventory/InventoryHelpers.kt
  app/src/main/kotlin/be/zvz/kookie/inventory/SimpleInventory.kt
  app/src/main/kotlin/be/zvz/kookie/item/Armor.kt
  app/src/main/kotlin/be/zvz/kookie/item/Item.kt
  app/src/main/kotlin/be/zvz/kookie/item/ItemFactory.kt
  app/src/main/kotlin/be/zvz/kookie/item/enchantment/EnchantmentIdMap.kt
  app/src/main/kotlin/be/zvz/kookie/item/enchantment/ProtectionEnchantment.kt
  app/src/main/kotlin/be/zvz/kookie/lang/TranslationContainer.kt
  app/src/main/kotlin/be/zvz/kookie/math/Facing.kt
  app/src/main/kotlin/be/zvz/kookie/math/Vector3.kt
  app/src/main/kotlin/be/zvz/kookie/nbt/BaseNbtSerializer.kt
  app/src/main/kotlin/be/zvz/kookie/nbt/BigEndianNbtSerializer.kt
  app/src/main/kotlin/be/zvz/kookie/nbt/LittleEndianNbtSerializer.kt
  app/src/main/kotlin/be/zvz/kookie/nbt/tag/CompoundTag.kt
  app/src/main/kotlin/be/zvz/kookie/nbt/tag/ListTag.kt
  app/src/main/kotlin/be/zvz/kookie/network/Network.kt
  app/src/main/kotlin/be/zvz/kookie/network/mcpe/NetworkSession.kt
  app/src/main/kotlin/be/zvz/kookie/network/mcpe/convert/ItemTranslator.kt
  app/src/main/kotlin/be/zvz/kookie/network/mcpe/convert/LegacySkinAdapter.kt
  app/src/main/kotlin/be/zvz/kookie/network/mcpe/protocol/AddActorPacket.kt
  app/src/main/kotlin/be/zvz/kookie/network/mcpe/protocol/AddPlayerPacket.kt
  app/src/main/kotlin/be/zvz/kookie/network/mcpe/protocol/AvailableCommandsPacket.kt
  app/src/main/kotlin/be/zvz/kookie/network/mcpe/protocol/ClientCacheBlobStatusPacket.kt
  app/src/main/kotlin/be/zvz/kookie/network/mcpe/protocol/ClientboundMapItemDataPacket.kt
  app/src/main/kotlin/be/zvz/kookie/network/mcpe/protocol/CommandOutputPacket.kt
  app/src/main/kotlin/be/zvz/kookie/network/mcpe/protocol/EducationSettingsPacket.kt
  app/src/main/kotlin/be/zvz/kookie/network/mcpe/protocol/EmoteListPacket.kt
  app/src/main/kotlin/be/zvz/kookie/network/mcpe/protocol/LevelChunkPacket.kt
  app/src/main/kotlin/be/zvz/kookie/network/mcpe/protocol/PlayerFogPacket.kt
  app/src/main/kotlin/be/zvz/kookie/network/mcpe/protocol/PurchaseReceiptPacket.kt
  app/src/main/kotlin/be/zvz/kookie/network/mcpe/protocol/ResourcePackClientResponsePacket.kt
  app/src/main/kotlin/be/zvz/kookie/network/mcpe/protocol/StartGamePacket.kt
  app/src/main/kotlin/be/zvz/kookie/network/mcpe/protocol/StructureTemplateDataResponsePacket.kt
  app/src/main/kotlin/be/zvz/kookie/network/mcpe/protocol/TextPacket.kt
  app/src/main/kotlin/be/zvz/kookie/network/mcpe/protocol/UpdateSoftEnumPacket.kt
  app/src/main/kotlin/be/zvz/kookie/network/mcpe/protocol/serializer/NetworkNbtSerializer.kt
  app/src/main/kotlin/be/zvz/kookie/network/mcpe/protocol/serializer/PacketSerializer.kt
  app/src/main/kotlin/be/zvz/kookie/network/mcpe/protocol/types/Experiments.kt
  app/src/main/kotlin/be/zvz/kookie/network/mcpe/protocol/types/inventory/InventoryTransactionChangedSlotsHack.kt
  app/src/main/kotlin/be/zvz/kookie/network/mcpe/protocol/types/inventory/stackrequest/DeprecatedCraftingResultsStackRequestAction.kt
  app/src/main/kotlin/be/zvz/kookie/network/mcpe/protocol/types/inventory/stackrequest/ItemStackRequest.kt
  app/src/main/kotlin/be/zvz/kookie/network/mcpe/protocol/types/recipe/ShapedRecipe.kt
  app/src/main/kotlin/be/zvz/kookie/network/mcpe/protocol/types/recipe/ShapelessRecipe.kt
  app/src/main/kotlin/be/zvz/kookie/network/mcpe/raklib/RakLibInterface.kt
  app/src/main/kotlin/be/zvz/kookie/permission/PermissibleBase.kt
  app/src/main/kotlin/be/zvz/kookie/permission/PermissionAttachment.kt
  app/src/main/kotlin/be/zvz/kookie/permission/PermissionManager.kt
  app/src/main/kotlin/be/zvz/kookie/utils/inline/CollectionExtension.kt
  app/src/main/kotlin/be/zvz/kookie/utils/inline/IteratorExtension.kt
  app/src/main/kotlin/be/zvz/kookie/world/BlockTransaction.kt
  app/src/main/kotlin/be/zvz/kookie/world/format/internal/InternalPalettedBlockArray.kt
  app/src/main/kotlin/be/zvz/kookie/world/format/io/SubChunkConverter.kt
Labels: low priority, style

#22 feature: Command system
  app/src/main/kotlin/be/zvz/kookie/Server.kt
  app/src/main/kotlin/be/zvz/kookie/command/Command.kt
  app/src/main/kotlin/be/zvz/kookie/command/CommandMap.kt
  app/src/main/kotlin/be/zvz/kookie/command/SimpleCommandMap.kt
  app/src/main/kotlin/be/zvz/kookie/command/defaults/ClearCommand.kt
  app/src/main/kotlin/be/zvz/kookie/command/defaults/VanillaCommand.kt
  app/src/main/kotlin/be/zvz/kookie/lang/Language.kt
  app/src/main/kotlin/be/zvz/kookie/lang/TranslationContainer.kt
  app/src/main/kotlin/be/zvz/kookie/network/mcpe/protocol/AvailableCommandsPacket.kt
  app/src/main/kotlin/be/zvz/kookie/permission/BanEntry.kt
  app/src/main/kotlin/be/zvz/kookie/permission/BanList.kt
Labels: enhancement, normal priority

#34 feature: InventoryTransaction
  app/src/main/kotlin/be/zvz/kookie/inventory/transaction/InventoryTransaction.kt
  app/src/main/kotlin/be/zvz/kookie/inventory/transaction/TransactionValidationException.kt
  app/src/main/kotlin/be/zvz/kookie/inventory/transaction/action/CreateItemAction.kt
  app/src/main/kotlin/be/zvz/kookie/inventory/transaction/action/DestroyItemAction.kt
  app/src/main/kotlin/be/zvz/kookie/inventory/transaction/action/DropItemAction.kt
  app/src/main/kotlin/be/zvz/kookie/inventory/transaction/action/InventoryAction.kt
  app/src/main/kotlin/be/zvz/kookie/inventory/transaction/action/SlotChangeAction.kt
Labels: enhancement

#36 feature: Crafting
  app/src/main/kotlin/be/zvz/kookie/crafting/CraftingGrid.kt
  app/src/main/kotlin/be/zvz/kookie/crafting/CraftingManager.kt
  app/src/main/kotlin/be/zvz/kookie/crafting/CraftingManagerFromDataHelper.kt
  app/src/main/kotlin/be/zvz/kookie/crafting/CraftingRecipe.kt
  app/src/main/kotlin/be/zvz/kookie/crafting/FurnaceRecipe.kt
  app/src/main/kotlin/be/zvz/kookie/crafting/FurnaceRecipeManager.kt
  app/src/main/kotlin/be/zvz/kookie/crafting/ShapedRecipe.kt
  app/src/main/kotlin/be/zvz/kookie/crafting/ShapelessRecipe.kt
  app/src/main/kotlin/be/zvz/kookie/crafting/utils/FurnaceRecipeData.kt
  app/src/main/kotlin/be/zvz/kookie/crafting/utils/ItemData.kt
  app/src/main/kotlin/be/zvz/kookie/crafting/utils/ShapedRecipeData.kt
  app/src/main/kotlin/be/zvz/kookie/crafting/utils/ShapelessRecipeData.kt
Labels: enhancement, normal priority

#37 hotfix: missing transaction
  app/src/main/kotlin/be/zvz/kookie/inventory/transaction/CraftingTransaction.kt
  app/src/main/kotlin/be/zvz/kookie/inventory/transaction/InventoryTransaction.kt
  app/src/main/kotlin/be/zvz/kookie/player/Player.kt
Labels: enhancement, normal priority
